"""
Trading signal models
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field
from .base import SignalType


class Signal(BaseModel):
    """Trading signal generated by an algorithm"""

    algorithm_id: str = Field(..., description="ID of the algorithm that generated the signal")
    symbol: str = Field(..., description="Trading symbol")
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    signal_type: SignalType = Field(..., description="BUY, SELL, or HOLD")
    confidence: float = Field(..., ge=0, le=1, description="Confidence score (0-1)")

    # Optional price targets
    target_price: Optional[float] = Field(None, gt=0, description="Target price for the signal")
    stop_loss: Optional[float] = Field(None, gt=0, description="Stop loss price")

    # Context
    reason: Optional[str] = Field(None, description="Explanation for the signal")

    # Position sizing suggestion
    suggested_quantity: Optional[float] = Field(None, gt=0, description="Suggested quantity to trade")

    class Config:
        json_schema_extra = {
            "example": {
                "algorithm_id": "sma_crossover_v1",
                "symbol": "AAPL",
                "timestamp": "2025-11-09T10:30:00",
                "signal_type": "BUY",
                "confidence": 0.75,
                "target_price": 180.00,
                "stop_loss": 170.00,
                "reason": "20-day SMA crossed above 50-day SMA",
                "suggested_quantity": 10
            }
        }
